weather_safety_tips = {
    200: "🌩️ Thunderstorm with light rain\nSAFETY TIP: ⚡ Stay indoors if possible. 🏠 Avoid open areas and tall objects 🌳.",
    201: "⛈️ Thunderstorm with rain\nSAFETY TIP: ⚡ Avoid outdoor activities 🚶‍♂️ and unplug electrical devices 🔌.",
    202: "🌪️ Thunderstorm with heavy rain\nSAFETY TIP: ⚠️ Stay inside 🏠, avoid driving 🚗, and watch for flash floods 🌊.",
    210: "🌩️ Light thunderstorm\nSAFETY TIP: ⚡ Be cautious outdoors 🏃 and stay away from open fields 🌳.",
    211: "⛈️ Thunderstorm\nSAFETY TIP: ⚡ Seek shelter indoors 🏠 and avoid using electrical appliances 🔋.",
    212: "🌪️ Heavy thunderstorm\nSAFETY TIP: ⚠️ Stay indoors, close windows 🪟, and avoid large trees 🌲.",
    221: "🌩️ Ragged thunderstorm\nSAFETY TIP: 🏠 Find a sturdy shelter and avoid standing near metal objects ⚡.",
    230: "🌩️ Thunderstorm with light drizzle\nSAFETY TIP: ☔ Carry an umbrella but stay alert for lightning ⚠️.",
    231: "⛈️ Thunderstorm with drizzle\nSAFETY TIP: ⚡ Avoid open spaces and stay indoors if possible 🏠.",
    232: "🌪️ Thunderstorm with heavy drizzle\nSAFETY TIP: ⚠️ Drive cautiously 🚗 and avoid flooded areas 🌊.",

    300: "🌧️ Light intensity drizzle\nSAFETY TIP: ☂️ A light raincoat or umbrella will help.",
    301: "🌦️ Drizzle\nSAFETY TIP: ☔ Carry an umbrella and wear waterproof clothing 🧥.",
    302: "🌧️ Heavy intensity drizzle\nSAFETY TIP: 🌂 Use a waterproof jacket and avoid staying outside for long.",
    310: "🌦️ Light intensity drizzle rain\nSAFETY TIP: ☔ Use an umbrella or raincoat.",
    311: "🌧️ Drizzle rain\nSAFETY TIP: 🚗 Be cautious while driving, roads may be slippery ⚠️.",
    312: "🌧️ Heavy intensity drizzle rain\nSAFETY TIP: 👟 Wear waterproof shoes to avoid slipping.",
    313: "🌦️ Shower rain and drizzle\nSAFETY TIP: ☂️ Carry an umbrella and be prepared for sudden rain.",
    314: "🌧️ Heavy shower rain and drizzle\nSAFETY TIP: ⚠️ Avoid waterlogged areas and wear waterproof gear.",
    321: "🌦️ Shower drizzle\nSAFETY TIP: ☔ Use an umbrella and avoid long outdoor exposure.",

    500: "🌦️ Light rain\nSAFETY TIP: ☂️ Carry an umbrella or raincoat.",
    501: "🌧️ Moderate rain\nSAFETY TIP: 🧥 Wear waterproof clothing and be careful while walking on wet surfaces.",
    502: "🌧️ Heavy intensity rain\nSAFETY TIP: 🚗 Stay indoors if possible and avoid driving through flooded roads 🌊.",
    503: "🌧️ Very heavy rain\nSAFETY TIP: ⚠️ Flooding possible—avoid low-lying areas 🌊.",
    504: "🌧️ Extreme rain\nSAFETY TIP: ⚠️ Serious flooding risk—stay indoors and monitor weather updates 📢.",
    511: "❄️ Freezing rain\nSAFETY TIP: ❄️ Roads will be slippery—drive carefully or avoid travel 🚗.",
    520: "🌦️ Light intensity shower rain\nSAFETY TIP: ☂️ Keep an umbrella handy.",
    521: "🌧️ Shower rain\nSAFETY TIP: 🧥 Wear a raincoat and avoid biking 🚲 on slippery roads.",
    522: "🌧️ Heavy intensity shower rain\nSAFETY TIP: ⚠️ Watch for flooding and avoid outdoor activities.",
    531: "🌧️ Ragged shower rain\nSAFETY TIP: 🏠 Stay indoors if possible and avoid driving 🚗.",

    600: "🌨️ Light snow\nSAFETY TIP: 🧥 Wear warm clothes and non-slip shoes 👢.",
    601: "❄️ Snow\nSAFETY TIP: 🚗 Drive carefully, and keep emergency supplies in your car.",
    602: "❄️ Heavy snow\nSAFETY TIP: ⚠️ Avoid travel unless necessary—carry emergency gear 🎒.",
    611: "🌨️ Sleet\nSAFETY TIP: 🚶 Be extra cautious while walking or driving.",
    612: "🌨️ Light shower sleet\nSAFETY TIP: 🧤 Wear insulated clothing and use caution outside.",
    613: "🌨️ Shower sleet\nSAFETY TIP: 🚗 Avoid driving unless necessary.",
    615: "🌧️ Light rain and snow\nSAFETY TIP: ⚠️ Watch for slippery surfaces.",
    616: "🌧️ Rain and snow\nSAFETY TIP: 🚗 Drive carefully and wear warm waterproof clothing 🧥.",
    620: "🌨️ Light shower snow\nSAFETY TIP: 🧣 Use warm layers and waterproof boots.",
    621: "🌨️ Shower snow\nSAFETY TIP: ⚠️ Avoid unnecessary travel, especially on highways 🛣️.",
    622: "❄️ Heavy shower snow\nSAFETY TIP: 🚨 Serious travel disruptions possible—stay indoors 🏠.",

    701: "🌫️ Mist\nSAFETY TIP: 🚗 Drive with fog lights and slow down.",
    711: "💨 Smoke\nSAFETY TIP: 😷 Wear a mask if air quality is poor.",
    721: "🌫️ Haze\nSAFETY TIP: ⚠️ Reduce outdoor activities if you have breathing issues.",
    731: "🌪️ Sand/Dust whirls\nSAFETY TIP: 😷 Wear a dust mask and protect your eyes 👀.",
    741: "🌫️ Fog\nSAFETY TIP: 🚗 Use fog lights and drive slowly.",
    751: "🏜️ Sand\nSAFETY TIP: 🏠 Stay indoors and protect your face if going outside.",
    761: "💨 Dust\nSAFETY TIP: 😷 Avoid outdoor exposure—wear a mask.",
    762: "🌋 Volcanic ash\nSAFETY TIP: 🚪 Stay indoors, and use air purifiers.",
    771: "🌬️ Squalls\nSAFETY TIP: 🌊 Stay away from open water and secure loose objects.",
    781: "🌪️ Tornado\nSAFETY TIP: 🏠 Take shelter in a basement or sturdy building.",

    800: "☀️ Clear sky\nSAFETY TIP: 😎 Enjoy the day! Use sunscreen 🧴 if it's sunny.",

    801: "⛅ Few clouds (11-25%)\nSAFETY TIP: 🌤️ Mild weather, no special precautions.",
    802: "🌤️ Scattered clouds (25-50%)\nSAFETY TIP: 🥤 A pleasant day, but stay hydrated if it's hot.",
    803: "🌥️ Broken clouds (51-84%)\nSAFETY TIP: ☁️ Cloudy but comfortable.",
    804: "☁️ Overcast clouds (85-100%)\nSAFETY TIP: 🌫️ It may feel gloomy, but no major concerns.",
}
